# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Hn',
        ),
        migrations.RenameField(
            model_name='hn',
            old_name='hn',
            new_name='hn_dict',
        ),
    ]
