# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0002_auto_20160417_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hn',
            old_name='hn_dict',
            new_name='All_items_dict',
        ),
    ]
