# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('namelist', '0003_auto_20160412_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='adress',
        ),
        migrations.AddField(
            model_name='adress',
            name='Name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='namelist.Name'),
            preserve_default=False,
        ),
    ]
