# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namelist', '0004_auto_20160412_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='img_house',
            field=models.ImageField(blank=True, upload_to='files'),
        ),
    ]
