# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('namelist', '0006_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='Name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='namelist.Name'),
            preserve_default=False,
        ),
    ]
