# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namelist', '0007_tasks_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='Name',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
